<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>_26310022_kimduk_GameProject</RootNamespace>
    <AssemblyName>26310022_kimduk_GameProject</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Update="..\resource\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="resource\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="glc2dcsharp" Version="0.1.0.6" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.WinForms" Version="3.8.3" />
    <PackageReference Include="Vortice.XAudio2" Version="3.8.3" />
    <PackageReference Include="Vortice.XInput" Version="3.8.3" />
  </ItemGroup>

</Project>
